language:
- cpp
os:
- linux
- osx
compiler:
- gcc
addons:
  apt:
    packages:
      - google-perftools
      - libgoogle-perftools-dev
      - cmake
      - libgtest-dev
      
before_install: tools/travis_before_install.sh
install: tools/travis_install.sh
script: tools/travis_script.sh

notifications:
  email: false
  slack:
    secure